[project]
name = "app_developer"
version = "0.1.0"
description = "app-developer using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.9.2"
]

[project.scripts]
app_developer = "app_developer.main:run"
run_crew = "app_developer.main:run"
train = "app_developer.main:train"
replay = "app_developer.main:replay"
test = "app_developer.main:test"
run_with_trigger = "app_developer.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
